### PR TITLE
split source directory into main and test.

### LINKED ISSUE #28: Add tests in the structure
FYI https://github.com/numero-744/Aes has been updated; part of its contents could be put in the template:

* add `tb/` folder for `Test` (not released contents) with sub-directories like for `hw/`
* add HTML report generation with `scalatest`
* works with both App and SpinalTestBench (in its current state, changes will occur)
* tested with `mill`

See the end of the [readme](https://github.com/numero-744/Aes#aes-a-spinal-demo-project) with an IDE screenshot and the resulting directory structure with important things highlighted in blue on the left.

### PR DESCRIPTION
**Pull request by Readon**
close #28

### CODE REVIEW

**Comment by numero-744** [comment]
Wasn't my suggestion with `hw` and `tb` okay?

**Comment by Readon** [comment]
> Wasn't my suggestion with `hw` and `tb` okay?
> 
> It is working in my AES repository. Also I had planned to push stuff from this repo soon

ahh, I misundertood. use tb to fit the leg ency of hardware design community?

**Comment by numero-744** [comment]
Exactly

**Comment by numero-744** [comment]
https://github.com/SpinalHDL/SpinalTemplateSbt/issues/28#issuecomment-1341476638

**Pull request closed without merging**
